### ISSUE TITLE
[BUG] Musicbox stops working on Paper 1.18.1

### ISSUE THREAD

**Issue by Tsoccerguy3** [Spliterash/MusicBox#18]
After setting up the Musicbox it will play a few songs and then the plugin breaks . No errors in log , nothing in console . . I need to break this Musicbox and make it again . You can not put records in the box while playing this may break it as well

![2021-12-17_04 30 27](https://user-images.githubusercontent.com/22108822/146522918-3987ea98-8428-4b45-b2af-4550bc059e3a.png)
![2021-12-17_04 31 46](https://user-images.githubusercontent.com/22108822/146522921-60efd876-1ec8-44d5-a62b-9a29c73d5c63.png)
![2021-12-17_04 31 56](https://user-images.githubusercontent.com/22108822/146522924-b56e101f-9936-4d3a-9e3b-7de34a800eaf.png)

**Comment by Tsoccerguy3** [comment]
After a disc is played or removed from a jukebox or sits in the menu , the discs are recongnised as a Misc Disc and no longer work in your Musicbox

![2021-12-17_04 53 10](https://user-images.githubusercontent.com/22108822/146525703-871e349f-f34d-4cb6-811d-b98afd2a6a8f.png)

**Comment by Spliterash** [comment]
Okay, take look

**Comment by Spliterash** [comment]
I can't repeat, tell me what version of the server you have(spigot, paper or another) with version, and are there any plugins that affect items?

**Comment by Tsoccerguy3** [comment]
Paper 1.18.1 build 77

**Comment by Tsoccerguy3** [comment]
if you want to try out the plugin on Paper 1.18.1 do /plot auto to get a plot in creative mode https://www.planetminecraft.com/server/sanacraft/

**Comment by Spliterash** [comment]
Dont have pex to take musicbox discs

**Comment by Tsoccerguy3** [comment]
I set you to server member iron worker , Try , /plot auto to get a plot to build test musicbox.

**Comment by Tsoccerguy3** [comment]
I have Op and doing the tests . The plugin is causing errors with your custom NoteblockAPI . Lots of errors . I dont want to set perms yet , because the plugin is broken on Paper 1.18.1 . The songs are playing in random locations as well .


[17:22:26 ERROR]: An error occurred during the playback of song plugins/MusicBox/songs/Games/TobyFox/Hopes And Dream.nbs ( - Hopes And Dream)
[17:22:26 WARN]: java.lang.IllegalStateException: PlayerRangeStateChangeEvent may only be triggered synchronously.
[17:22:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616)
[17:22:26 WARN]:        at NoteBlockAPI-1.6.2-SNAPSHOT.jar//com.xxmicloxx.NoteBlockAPI.songplayer.PositionSongPlayer.playTick(PositionSongPlayer.java:100)
[17:22:26 WARN]:        at NoteBlockAPI-1.6.2-SNAPSHOT.jar//com.xxmicloxx.NoteBlockAPI.songplayer.SongPlayer.lambda$start$7(SongPlayer.java:440)
[17:22:26 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:22:26 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:22:26 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:22:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:22:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:22:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:22:36 ERROR]: An error occurred during the playback of song plugins/MusicBox/songs/Games/TobyFox/Hopes And Dream.nbs ( - Hopes And Dream)
[17:22:59 ERROR]: An error occurred during the playback of song plugins/MusicBox/songs/Games/TobyFox/Scarlet Forest.nbs (Toby Fox - Scarlet Forest)
[17:22:59 WARN]: java.lang.IllegalStateException: PlayerRangeStateChangeEvent may only be triggered synchronously.
[17:22:59 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616)
[17:22:59 WARN]:        at NoteBlockAPI-1.6.2-SNAPSHOT.jar//com.xxmicloxx.NoteBlockAPI.songplayer.PositionSongPlayer.playTick(PositionSongPlayer.java:100)
[17:22:59 WARN]:        at NoteBlockAPI-1.6.2-SNAPSHOT.jar//com.xxmicloxx.NoteBlockAPI.songplayer.SongPlayer.lambda$start$7(SongPlayer.java:440)
[17:22:59 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:22:59 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:22:59 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:22:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:22:59 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:22:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:23:01 ERROR]: An error occurred during the playback of song plugins/MusicBox/songs/Games/TobyFox/Spear of Justice.nbs (Tobyfox - Spear of Justice)
[17:23:01 WARN]: java.lang.IllegalStateException: PlayerRangeStateChangeEvent may only be triggered synchronously.
[17:23:01 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:616)
[17:23:01 WARN]:        at NoteBlockAPI-1.6.2-SNAPSHOT.jar//com.xxmicloxx.NoteBlockAPI.songplayer.PositionSongPlayer.playTick(PositionSongPlayer.java:100)
[17:23:01 WARN]:        at NoteBlockAPI-1.6.2-SNAPSHOT.jar//com.xxmicloxx.NoteBlockAPI.songplayer.SongPlayer.lambda$start$7(SongPlayer.java:440)
[17:23:01 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:23:01 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:23:01 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:23:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:23:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:23:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Tsoccerguy3** [comment]
The errors to serious . we stopped testing and removed plugin , sorry
