### ISSUE TITLE
Could not pass event PlayerInteractEvent to MusicBox (1.20.6 ?)

### ISSUE THREAD

**Issue by LEMIBANDDEXARI** [Spliterash/MusicBox#37]
I'm using MusicBox v2.1.0 and paper-1.20.6-35
I know that MusicBox is not yet supported in 1.20.5/6 but if that helps you.
And thank you already for what you have done.

I have this error message on my server in 1.20.6

`[13:41:03 ERROR]: Could not pass event PlayerInteractEvent to MusicBox v2.1.0
java.lang.NoClassDefFoundError: Could not initialize class ru.spliterash.musicbox.
shadow.nbteditor.NBTEditor
        at MusicBox-2.1.0-all.jar/ru.spliterash.musicbox.song.MusicBoxSongManager.
findByItem(MusicBoxSongManager.java:85) ~[MusicBox-2.1.0-all.jar:?]
        at MusicBox-2.1.0-all.jar/ru.spliterash.musicbox.customPlayers.objects.juk
ebox.JukeboxPlayer.onJukeboxClick(JukeboxPlayer.java:44) ~[MusicBox-2.1.0-all.jar:
?]
        at MusicBox-2.1.0-all.jar/ru.spliterash.musicbox.Handler.onInteract(Handle
r.java:156) ~[MusicBox-2.1.0-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExec
utor87.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pape
r-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
 ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:git-Paper-36]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:
70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventM
anager.java:54) ~[paper-1.20.6.jar:git-Paper-36]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperP
luginManagerImpl.java:131) ~[paper-1.20.6.jar:git-Paper-36]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.jav
a:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(
CraftEventFactory.java:593) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerG
ameMode.java:531) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem
On(ServerGamePacketListenerImpl.java:1931) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(S
erverboundUseItemOnPacket.java:44) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(S
erverboundUseItemOnPacket.java:11) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameTh
read$0(PacketUtils.java:55) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:
git-Paper-36]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLo
op.java:151) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(Reentra
ntBlockableEventLoop.java:24) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:151
5) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:198
) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoo
p.java:125) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.j
ava:1492) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1415
) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEven
tLoop.java:135) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:15
66) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:123
5) ~[paper-1.20.6.jar:git-Paper-36]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java
:326) ~[paper-1.20.6.jar:git-Paper-36]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ArrayIndexOu
tOfBoundsException: Index 3 out of bounds for length 3 [in thread "Server thread"]
        at MusicBox-2.1.0-all.jar/ru.spliterash.musicbox.shadow.nbteditor.NBTEdito
r.<clinit>(NBTEditor.java:60) ~[MusicBox-2.1.0-all.jar:?]
        ... 29 more`

**Comment by DaddyRobLIVE** [comment]
bump, please notice dev.

**Comment by M1B4ND** [comment]
Now I'm using MusicBox v2.1.1 and paper-1.20.6-138
I get this error message when I go to one of the music categories, and also no music is displayed.

```
[22:12:50 ERROR]: Could not pass event InventoryClickEvent to MusicBox v2.1.1
java.lang.ExceptionInInitializerError: null
        at MusicBox-2.1.1-all.jar/ru.spliterash.musicbox.song.MusicBoxSong.getSongStack(MusicBoxSong.java:76) ~[MusicBox-2.1.1-all.jar:?]
        at MusicBox-2.1.1-all.jar/ru.spliterash.musicbox.song.MusicBoxSong.getSongStack(MusicBoxSong.java:58) ~[MusicBox-2.1.1-all.jar:?]
        at MusicBox-2.1.1-all.jar/ru.spliterash.musicbox.gui.song.SongContainerGUI.openPage(SongContainerGUI.java:120) ~[MusicBox-2.1.1-all.jar:?]
        at MusicBox-2.1.1-all.jar/ru.spliterash.musicbox.gui.song.SongContainerGUI.lambda$openPage$3(SongContainerGUI.java:103) ~[MusicBox-2.1.1-all.jar:?]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at MusicBox-2.1.1-all.jar/ru.spliterash.musicbox.minecraft.gui.actions.ClickAction.onEvent(ClickAction.java:27) ~[MusicBox-2.1.1-all.jar:?]
        at MusicBox-2.1.1-all.jar/ru.spliterash.musicbox.minecraft.gui.GUI.onInventoryClick(GUI.java:92) ~[MusicBox-2.1.1-all.jar:?]
        at MusicBox-2.1.1-all.jar/ru.spliterash.musicbox.minecraft.gui.GUI$1.onClick(GUI.java:29) ~[MusicBox-2.1.1-all.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-138-906df69]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3177) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-138-906df69]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at MusicBox-2.1.1-all.jar/ru.spliterash.musicbox.shadow.nbteditor.NBTEditor.<clinit>(NBTEditor.java:60) ~[MusicBox-2.1.1-all.jar:?]
        ... 31 more
```

**Comment by M1B4ND** [comment]
I don't know if it's just me but 2.1.2 doesn't work either

**Comment by M1B4ND** [comment]
I don't know if it's just me but 2.1.2 doesn't work either

**Comment by SandTripper** [comment]
Me too
