### ISSUE TITLE
1.21.1 Music Discs not working

### ISSUE THREAD

**Issue by LadyHaley** [Spliterash/MusicBox#38]
When I try to use a music disk I get this error and its gone forever
`[09:02:13 ERROR]: Could not pass event PlayerInteractEvent to MusicBox v2.1.2
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MusicBox-2.1.2-all.jar/ru.spliterash.musicbox.minecraft.nms.jukebox.JukeboxFactory.getJukebox(JukeboxFactory.java:78) ~[MusicBox-2.1.2-all.jar:?]
        at MusicBox-2.1.2-all.jar/ru.spliterash.musicbox.customPlayers.objects.jukebox.JukeboxPlayer.onJukeboxClick(JukeboxPlayer.java:51) ~[MusicBox-2.1.2-all.jar:?]
        at MusicBox-2.1.2-all.jar/ru.spliterash.musicbox.Handler.onInteract(Handler.java:156) ~[MusicBox-2.1.2-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1816.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-65-21f125f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:604) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1942) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-65-21f125f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at MusicBox-2.1.2-all.jar/ru.spliterash.musicbox.minecraft.nms.jukebox.JukeboxFactory.getJukebox(JukeboxFactory.java:75) ~[MusicBox-2.1.2-all.jar:?]
        ... 29 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at MusicBox-2.1.2-all.jar/ru.spliterash.musicbox.minecraft.nms.OldNmsUtils.getOldNmsPackage(OldNmsUtils.java:14) ~[MusicBox-2.1.2-all.jar:?]
        at MusicBox-2.1.2-all.jar/ru.spliterash.musicbox.minecraft.nms.OldNmsUtils.getNMSClass(OldNmsUtils.java:9) ~[MusicBox-2.1.2-all.jar:?]
        at MusicBox-2.1.2-all.jar/ru.spliterash.musicbox.minecraft.nms.jukebox.versions.V13_16.<init>(V13_16.java:15) ~[MusicBox-2.1.2-all.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
        at MusicBox-2.1.2-all.jar/ru.spliterash.musicbox.minecraft.nms.jukebox.JukeboxFactory.getJukebox(JukeboxFactory.java:75) ~[MusicBox-2.1.2-all.jar:?]
        ... 29 more`
        
   
Server is running Paper version 1.21.1 Build 65
Plugins are
AdvancedBan, AdvancedServerList, ajLeaderboards, ArmorStandAdjustor, ArmorTrimEdit, BannerMaker, BlockLocker, BlueMap, BreweryX, ChatColor, Citizens, ClearLag, CMI, CMILib, Cosmin, CreeperRecover, CustomCrafting, CustomCrops, DecentHolograms, DeluxeMentions, DiscordSRV, DropEdit2, DtlPlayershops, dtlTraders, DualHorse, DurabilityAlertReloaded, Dwellin, EnchantGui, EntityTraveller, ExcellentCrates, ExcellentEnchants, ExtractableEnchantments, FairyChat, FastAsyncWorldEdit, floodgate, FlowerMeal, Gender, GSit, Harbor, HeadDatabase, HuskHomes, IllegalStack, ImageFrame, InteractionVisualizer, InvisibleItemFrames, Jobs, LibsDisguises, Lootin, LuckPerms, Magic, MapModCompanion, MarriageMaster, mcMMO, McmmoGuiV2, Multiverse-Core, MusicBox, MyPet, MythicCrucible, MythicMobs, MythicMobsExtension, nightcore, NoteBlockAPI, Oraxen, OreAnnouncer, packetevents, PeacefulPlayerRepacified, PhantomSpawnControl, PlaceholderAPI, PlayerParticles, PlugManX, ProtocolLib, PyroFishingPro, PyroLib, PyroMining, QualityArmory, RealScoreboard, RocketJoin, Sentinel, ServerSigns, SkinsRestorer, SpawnerMeta, Spicord, StripArmour, SwimmingHorses, TogglePvp, VampireRevamp, Vault, ViaBackwards, ViaVersion, Vivecraft-Spigot-Extensions, VotingPlugin, WanderingTrades, Werewolf, WolfyUtilities, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags, XConomy

Using commands to play sounds works fine, its just the music discs

**Comment by Spliterash** [comment]
hi, sry, didnt see this

https://github.com/Spliterash/MusicBox/releases/tag/2.1.3
